### ISSUE TITLE
Site not loading properly

### ISSUE THREAD

**Issue by SterArcher** [sledilnik/website#1329]
Hi!
We have noticed that the site is not loading properly. The last update timestamp is from Thursday, August 1, 2024 at 09:41. Below, you can see:

1. The page loads.
2. The chart shows.
3. The chart disappears.
4. The page finishes loading.

See video for example.

https://github.com/user-attachments/assets/3762132d-5b8f-4631-ab55-8ec96372786e

**Comment by kesma01** [comment]
Hi. Most probably, the second, DailyComparison graph is causing the issue. 
And i assume that the reason is missing data from 1.8 til now.
The NIJZ page from which we are scraping data has changed. Again :/ 
Not sure how we'll deal with this now and in the future.
This is just FYI comment. 
Sorry for the late reply and thank you for submiting the issue.

Br, Kesma

**Comment by SterArcher** [comment]
> Hi. Most probably, the second, DailyComparison graph is causing the issue. And i assume that the reason is missing data from 1.8 til now. The NIJZ page from which we are scraping data has changed. Again :/ Not sure how we'll deal with this now and in the future. This is just FYI comment. Sorry for the late reply and thank you for submiting the issue.
> 
> Br, Kesma

I think the easiest thing to do would be to remove this chart and leave others.

Alternatively we could just remove all charts and leave a banner something like this: The data is no longer collected. All of the data saved is accessible through our API (link). When referencing our data for your work, please include the citation (DOI).
