### ISSUE TITLE
UX: add Navigator or Scroll to our charts

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/website#243]
As we have more and more data points, out charts become unreadable. We have couple of options, that we could use:

**1. Scrollable area**
![image](https://user-images.githubusercontent.com/46861689/80562326-b2e4a100-89e7-11ea-9b75-d69307b8e89b.png)
https://www.highcharts.com/docs/chart-concepts/scrollbar
``scrollablePlotArea`` looks perfect for our problem, but when we enabled it, we has some redraw issues on charts (lines were not drawn until refresh - bug?) 

**2. Navigator (Highstock feature)**
![HC Navigator](https://www.highcharts.com/docs/stock/navigator.png)
https://www.highcharts.com/docs/stock/navigator
We tried it, but is somehow did not work on our HC version - need to check if we have latest version.

**Comment by breki** [comment]
I would add a third option, custom implementation similar to option 2. (but simpler) with a few interval buttons (and no bottom overview panel), which:
1. adjusts the chart level of detail based on the interval size - the longer the interval, less detail (and maybe a different chart type)
2. causes our app to only request the data needed for the view, instead of always loading the whole dataset staring from March 2020.

Option 1. is not very mobile-friendly, and the whole concept of only being able to see a small part of the timeline does not seem very appealing.

**Comment by umarovt** [comment]
I would agree with @breki. Adding example of suggested solution, which can be found on top of the presented graph: 1h, 6h, 12h, 1d, 1w, 1m, 3m, 6m, 1y, all.

https://www.coindesk.com/price/bitcoin

**Comment by lukarenko** [comment]
This was added long time ago by @miaerbus
