### ISSUE TITLE
7day positive tests + hospital beds = "black/red/... phase"

### ISSUE THREAD

**Issue by ajitam** [sledilnik/website#730]
I think that (now that we have this 5 phases) it would be a good idea to have some section on a page with current state and maybe "diff" to next phase. Something like that.
I would propose some UI but I think you have this things covered :)

btw - great job for the whole project

**Comment by lukarenko** [comment]
We might add phases for release of measures when we will have more trust that they are really achievable in near future. Currently our concern is more that we are still in growth. Otherwise these were added to SEIR model:
https://covid-19.sledilnik.org/sl/models
https://apps.lusy.fri.uni-lj.si/~janezz/zadnja-simulacija_V2.png

**Comment by ajitam** [comment]
I don't understand what you mean by "they are really achievable in near future"... sooner or later we will achieve them :) hopefully sooner.

Thanks for the links
